projects:
  booksquadapi:
    schemaPath: ../../../../../graphql/schema.json
    includes:
      - src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: /graphql
  backendbooksquad:
    schemaPath: ../../../../../graphql/schema.json
    includes:
      - src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: /graphql
extensions:
  amplify:
    version: 3
